# Generated by Django 5.1.7 on 2025-03-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('task_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TimeField()),
                ('task_due_date', models.DateField()),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Choose Status', max_length=25)),
                ('task_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Choose Priority', max_length=25)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_secured_webapp.taskcategory')),
            ],
        ),
    ]
