# Generated by Django 5.1.7 on 2025-03-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_secured_webapp', '0002_alter_actualtask_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='task_description',
            new_name='cat_desc',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='task_name',
            new_name='cat_name',
        ),
    ]
